version: '3.8'

services:

  rest:
    build: . 
    ports:
      - "9090:9090"  
    volumes:
      - .:/app
    command: go run src/server/restServer/restServer.go -b 0.0.0.0
    depends_on:
      - db

  grpc:
    build: .  
    ports:
      - "8080:8080"  
    volumes:
      - .:/app
    command: go run src/server/grpcServer/grpcServer.go -b 0.0.0.0
    depends_on:
      - db
      - rest

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: UserService
      MYSQL_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_data:/var/lib/mysql


