configs:
  prod:
    user_service_url:
      gurl: "${USER_SERVICE_URL}"
      rurl: "${USER_SERVICE_REST}"
    db_config:
      password: "${DATABASE_PASSWORD}"
      username: "${DATABASE_USERNAME}"
      host: "${DATABASE_HOST_URL}"
      databaseName: ${DATABASE_NAME}
  dev:
    user_service_url:
      gurl: "${USER_SERVICE_URL}" 
      rurl: "${USER_SERVICE_REST}"
    db_config:
      password: "${DATABASE_PASSWORD}"
      username: "${DATABASE_USERNAME}"
      host: "${DATABASE_HOST_URL}"
      databaseName: ${DATABASE_NAME}

  test:
    user_service_url:
      gurl: "${USER_SERVICE_URL}"
      rurl: "${USER_SERVICE_REST}"
    db_config:
      password: "${DATABASE_PASSWORD}"
      username: "${DATABASE_USERNAME}"
      host: "${DATABASE_HOST_URL}"
      databaseName: ${DATABASE_NAME}
