-- CREATE DATABASE IF NOT EXISTS UserService;

-- USE UserService;

CREATE TABLE IF NOT EXISTS USER (
  UserId VARCHAR(255) PRIMARY KEY,
  UserName VARCHAR(255)
);

INSERT INTO USER VALUES ("399", "Darshan");
INSERT INTO USER VALUES ("400", "Chirag");
INSERT INTO USER VALUES ("401", "Yash");
